### ISSUE TITLE
y-grid组件全选状态问题，取消一条选择，全选仍然勾选

### ISSUE THREAD

**Issue by 15910269080** [yonyouyc/ycloud#58]
# 问题现象
    y-grid组件点击全选，将所有数据选中，然后取消一条数据选中，全选状态没有消失

# 问题组件
    y-grid
# 预期结果
   点击全选，数据全部选中，取消一条数据选中，全选状态取消
# 实际结果

# 重现地址

**Comment by songhlc** [comment]
将全选变成一个computed属性并设置write
