### ISSUE TITLE
表格组件UI建议

### ISSUE THREAD

**Issue by lovezjj008** [yonyouyc/ycloud#83]
# 问题现象
我建议 表格组件 y-cell  这个class 加padding-top 和 padding-bottom, 数据多 上下没 间距, 看起来很拥挤;
# 问题组件

![1519463919 1](https://user-images.githubusercontent.com/17973334/36628040-da48c0ec-1986-11e8-8c3c-1febe596439f.jpg)

# 预期结果
![1519463994 1](https://user-images.githubusercontent.com/17973334/36628056-fc2cfafc-1986-11e8-8a46-d218a236b151.jpg)

# 实际结果

# 重现地址

**Comment by songhlc** [comment]
可以通过tdstyle 自定义需要的高度 暂时不处理
